name: gluco_scan
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

#----------------- PACKAGES -----------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.3.0
  intl: ^0.20.2
  logger: ^2.5.0
  lottie: ^3.3.1
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  flex_color_scheme: ^8.2.0
  flutter_native_splash: ^2.4.6
  uuid: ^4.4.2
  timezone: ^0.10.1
  

  # State management
  get: ^4.7.2
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  google_sign_in: ^6.3.0
  firebase_storage: ^12.4.5
  gauge_indicator: ^0.4.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #----------------- LOCAL ASSETS -----------------#
  assets:
    - assets/logos/
    - assets/images/animations/

  #----------------- LOCAL FONTS -----------------#
  fonts:
    - family: InstrumentSans
      fonts:
        - asset: assets/fonts/instrumentsans/InstrumentSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/instrumentsans/InstrumentSans-Italic.ttf
          style: italic
        - asset: assets/fonts/instrumentsans/InstrumentSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/instrumentsans/InstrumentSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/instrumentsans/InstrumentSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/instrumentsans/InstrumentSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/instrumentsans/InstrumentSans-Bold.ttf
          weight: 800
        - asset: assets/fonts/instrumentsans/InstrumentSans-BoldItalic.ttf
          weight: 800
          style: italic