// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8iIMQXWMv3W5ZqRptlHKnR97p_q4mXeo',
    appId: '1:398709230612:android:e5aa1cba2af43fc619ab01',
    messagingSenderId: '398709230612',
    projectId: 'glucoscanapp',
    storageBucket: 'glucoscanapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-qxuXgW3_gLopl-jOqO03U5VJ2F-V4Tk',
    appId: '1:398709230612:ios:9f8161f6e9f5386619ab01',
    messagingSenderId: '398709230612',
    projectId: 'glucoscanapp',
    storageBucket: 'glucoscanapp.firebasestorage.app',
    androidClientId: '398709230612-vin0urgtnhrmvlj8hda81nkd7lnejkrc.apps.googleusercontent.com',
    iosClientId: '398709230612-0upg074fdmfllbqjlftcoh37ur5a43j8.apps.googleusercontent.com',
    iosBundleId: 'com.example.glucoScan',
  );

}